// Shared model instructions, derived from Open Work Hub (see NOTICE).
export const POLICY_VERSION = 'assisted-26-v2';
export const INSTRUCTION =
  'Choose one legal landing that keeps you alive and clears lines. Prefer safe line clears now over speculative stacking. Use hold to make clears, including singles, doubles and triples; do not save I indefinitely for a Tetris. If the board has holes or height >= 8, stop attack preparation and reduce holes and height with available clears. Only defer a safe clear for a concrete, safer or stronger next-piece result shown in then. In a duel, send attacks while preserving survival. Follow state.strategy in priority order.';
export const RULES =
  '10x20 Tetris; 7-bag; move/rotate/hard drop; full rows clear on lock. Hold once per piece; empty hold consumes next. Top-out loss: stack overflow or active/next piece cannot fit. One decision commits to one landing. The engine follows a legal path one key at a time; reobserve after placement or if the plan becomes invalid. Gravity continues during requests and movement.';
export const STRATEGY = [
  '1. Survival: reject spawn_blocked=1 when an alternative survives. Unknown is not safe. Keep the spawn area open and leave room for incoming garbage; do not wait until top-out is imminent to lower the stack.',
  '2. Recovery: if self or a proposed result has holes > 0 or height >= 8, stop building a Tetris well. Prefer clears that reduce holes and height; use a held I for a single, double or triple when it helps. At height >= 12, lowering the stack is urgent. If no useful clear is available, avoid new holes and minimize height and sum_height. These are conservative strategy thresholds, not engine rules.',
  '3. Clear lines: compare now.clear first and inspect each then separately. Take safe available clears, including singles with attack=0. Skip a safe clear only for an explicitly shown next-piece result that improves survival, or clears more lines while keeping both boards hole-free and below height 8. An unknown future piece or a larger well is not a reason to skip a clear.',
  '4. Build only when no useful clear is available: keep a low, compact surface with no covered holes. A single edge well for a Tetris is optional while hole-free and below height 8; prefer it when I is available in current/next/hold. Do not grow a well beyond four rows, cover it, or add height just to increase ready_rows or filled_cells. Those numbers describe preparation, not lines cleared or an attack.',
  '5. Convert preparation into clears: take a safe four-line clear when available. Do not keep saving I or rebuilding a completed well. In a duel, prefer more attack among similarly safe clearing plans and use the opponent board to assess an immediate winning attack. In solo play, prioritize survival, lines and score. Fewer keys breaks otherwise equal ties.',
];
export const LEGEND =
  "Boards/shapes: rows top-down, columns left-right; x/y are zero-based. Board '.'=empty, G=garbage, other letters=locked tetrominoes; active is separate. Shape 1=occupied, 0=empty. Candidates are engine-computed legal landings. Each landing's x/y and slash-separated shape give its exact pose before rows clear; then poses apply after now's placement and line clears. now=first landing; then=alternative second landings (choose at most one, not a committed plan). hold=1 swaps; reserve=hold afterward ('-' empty). next/spawn_blocked unknown=no forecast; spawn_blocked=1 means top-out. clear=lines removed; attack=garbage sent in a duel; holes=covered empty cells; height=max column height; sum_height=sum of column heights; roughness=sum of adjacent height differences; keys=inputs to complete that landing. self/opponent surface metrics describe the current locked board; now/then metrics describe the board after that landing and its line clears. wells=comma-separated column:depth:ready_rows:filled_cells after that landing ('-' none). Each well is a one-column shaft open from above, bounded by neighbors or a board edge. Depth is measured from its floor to the lower adjacent surface. In the four rows just above its floor, ready_rows have all other nine cells filled; filled_cells counts those other cells (0..36). Four ready rows enable a vertical-I Tetris. These are board geometry, not a guarantee that the next I can reach it before gravity. Deeper than four is not extra preparation; height/holes still measure danger. total_clear/total_attack=now plus that then, never all alternatives together.";
export const ATTACK_RULES =
  "Both players: clear 1/2/3/4 -> attack 0/1/2/3. Garbage rises immediately; 1 independently random hole per row. No cancellation, combo or B2B bonuses. One Tetris sends 3; two doubles send 2 total. Use the opponent's board to assess finishing attacks and incoming danger.";
