// Shared model instructions, derived from Open Work Hub (see NOTICE).
export const POLICY_VERSION = 'assisted-26-v1';
export const INSTRUCTION =
  'Choose one landing to win, following state rules. Use 9-0 Tetris stacking while safe: build four rows around one open column and save I to attack. A safe setup is better than a single clear or merely lowering the board. Switch to survival clears for actual top-out danger, or attack immediately to finish the opponent.';
export const RULES =
  '10x20 Tetris; 7-bag; move/rotate/hard drop; full rows clear on lock. Hold once per piece; empty hold consumes next. Top-out loss: stack overflow or active/next piece cannot fit. One decision commits to one landing. The engine follows a legal path one key at a time; reobserve after placement or if the plan becomes invalid. Gravity continues during requests and movement.';
export const STRATEGY = [
  'Avoid actual top-out danger (blocked spawn, a stack near the spawn area, or buried holes preventing recovery). A modest height increase on a low, hole-free board is not such danger.',
  'Build for repeated Tetris (4-line clears), not only immediate clears. On a low, hole-free board, leave one column open and fill the other nine across four rows. Prefer an edge well when starting; preserve an existing useful well rather than switching sides.',
  'Prepare this stack over several pieces, even before I is visible; keep it modest while waiting. Reserve a visible I for the four-row well instead of spending it just to flatten the board. Use current/next/hold and each then alternative; do not assume hidden pieces or an I arrival time.',
  'Do not cover the well or bury holes. While safe, preserve attack preparation instead of taking a single clear for no attack. Accept a higher, rougher stack to increase well ready_rows and filled_cells; do not optimize minimum height or score at the expense of the setup. Abandon the setup to avoid top-out or finish the opponent.',
  'Among similarly safe plans: Tetris > total attack > fewer holes > lower height. A deliberate well may increase roughness. Fewer keys only breaks otherwise equal ties.',
];
export const LEGEND =
  "Boards/shapes: rows top-down, columns left-right; x/y are zero-based. Board '.'=empty, G=garbage, other letters=locked tetrominoes; active is separate. Shape 1=occupied, 0=empty. Candidates are engine-computed legal landings. Each landing's x/y and slash-separated shape give its exact pose before rows clear; then poses apply after now's placement and line clears. now=first landing; then=alternative second landings (choose at most one). hold=1 swaps; reserve=hold afterward ('-' empty). next/spawn_blocked unknown=no forecast; spawn_blocked=1 means top-out. clear=lines removed; attack=garbage sent in a duel; holes=covered empty cells; height=max column height; sum_height=sum of column heights; roughness=sum of adjacent height differences; keys=inputs to complete that landing. wells=comma-separated column:depth:ready_rows:filled_cells after that landing ('-' none). Each well is a one-column shaft open from above, bounded by neighbors or a board edge. Depth is measured from its floor to the lower adjacent surface. In the four rows just above its floor, ready_rows have all other nine cells filled; filled_cells counts those other cells (0..36). Four ready rows enable a vertical-I Tetris. These are board geometry, not a guarantee that the next I can reach it before gravity. Deeper than four is not extra preparation; height/holes still measure danger. total_clear/total_attack=now plus that then, never all alternatives together.";
export const ATTACK_RULES =
  "Both players: clear 1/2/3/4 -> attack 0/1/2/3. Garbage rises immediately; 1 independently random hole per row. No cancellation, combo or B2B bonuses. One Tetris sends 3; two doubles send 2 total. Use the opponent's board to assess finishing attacks and incoming danger.";
